-- Reference: Docs/audit_log_and_housekeeping_guide.md
-- Purpose: add usage audit logging + safe cleanup utilities for recommendation runs/results.
-- Safe default: cleanup functions support dry-run mode.

-- ---------------------------------------------------------------------------
-- 1) Audit log table
-- ---------------------------------------------------------------------------

create table if not exists public.app_audit_log (
  id bigint generated by default as identity primary key,
  event_time timestamptz not null default now(),
  actor_user_profile_id uuid null,
  event_name text not null,
  entity_table text not null,
  entity_id uuid null,
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists idx_app_audit_log_event_time
  on public.app_audit_log (event_time desc);

create index if not exists idx_app_audit_log_actor
  on public.app_audit_log (actor_user_profile_id, event_time desc);

create index if not exists idx_app_audit_log_event_name
  on public.app_audit_log (event_name, event_time desc);

-- ---------------------------------------------------------------------------
-- 2) Generic logging helper
-- ---------------------------------------------------------------------------

create or replace function public.log_app_event(
  p_actor_user_profile_id uuid,
  p_event_name text,
  p_entity_table text,
  p_entity_id uuid,
  p_metadata jsonb default '{}'::jsonb
)
returns void
language plpgsql
as $$
begin
  insert into public.app_audit_log (
    actor_user_profile_id,
    event_name,
    entity_table,
    entity_id,
    metadata
  )
  values (
    p_actor_user_profile_id,
    p_event_name,
    p_entity_table,
    p_entity_id,
    coalesce(p_metadata, '{}'::jsonb)
  );
end;
$$;

-- ---------------------------------------------------------------------------
-- 3) Triggers for recommendation_runs and recommendations
-- ---------------------------------------------------------------------------

create or replace function public.trg_log_recommendation_runs()
returns trigger
language plpgsql
as $$
begin
  if tg_op = 'INSERT' then
    perform public.log_app_event(
      new.user_profile_id,
      'recommendation_run_created',
      'recommendation_runs',
      new.id,
      jsonb_build_object(
        'strategy_type', new.strategy_type,
        'input_budget', new.input_budget,
        'max_out_of_pocket', new.max_out_of_pocket,
        'run_status', new.run_status
      )
    );
    return new;
  elsif tg_op = 'UPDATE' then
    perform public.log_app_event(
      new.user_profile_id,
      'recommendation_run_updated',
      'recommendation_runs',
      new.id,
      jsonb_build_object(
        'old_run_status', old.run_status,
        'new_run_status', new.run_status
      )
    );
    return new;
  elsif tg_op = 'DELETE' then
    perform public.log_app_event(
      old.user_profile_id,
      'recommendation_run_deleted',
      'recommendation_runs',
      old.id,
      jsonb_build_object(
        'strategy_type', old.strategy_type,
        'input_budget', old.input_budget,
        'max_out_of_pocket', old.max_out_of_pocket
      )
    );
    return old;
  end if;

  return null;
end;
$$;

drop trigger if exists trg_recommendation_runs_audit on public.recommendation_runs;
create trigger trg_recommendation_runs_audit
after insert or update or delete
on public.recommendation_runs
for each row
execute function public.trg_log_recommendation_runs();

create or replace function public.trg_log_recommendations()
returns trigger
language plpgsql
as $$
begin
  if tg_op = 'INSERT' then
    perform public.log_app_event(
      new.user_profile_id,
      'recommendation_created',
      'recommendations',
      new.id,
      jsonb_build_object(
        'recommendation_run_id', new.recommendation_run_id,
        'strategy_type', new.strategy_type,
        'top_suburbs_count', jsonb_array_length(coalesce(new.top_suburbs, '[]'::jsonb))
      )
    );
    return new;
  elsif tg_op = 'DELETE' then
    perform public.log_app_event(
      old.user_profile_id,
      'recommendation_deleted',
      'recommendations',
      old.id,
      jsonb_build_object(
        'recommendation_run_id', old.recommendation_run_id,
        'strategy_type', old.strategy_type
      )
    );
    return old;
  end if;

  return null;
end;
$$;

drop trigger if exists trg_recommendations_audit on public.recommendations;
create trigger trg_recommendations_audit
after insert or delete
on public.recommendations
for each row
execute function public.trg_log_recommendations();

-- ---------------------------------------------------------------------------
-- 4) Helpful indexes for dedupe/cleanup analysis
-- ---------------------------------------------------------------------------

create index if not exists idx_recommendation_runs_signature_created
  on public.recommendation_runs (
    user_profile_id,
    strategy_type,
    input_budget,
    max_out_of_pocket,
    created_at desc
  );

create index if not exists idx_recommendations_run_created
  on public.recommendations (recommendation_run_id, created_at desc);

-- ---------------------------------------------------------------------------
-- 5) Duplicate cleanup for recommendations table
--    Keeps latest recommendation per run_id, removes older duplicates.
-- ---------------------------------------------------------------------------

create or replace function public.cleanup_duplicate_recommendations_per_run(
  p_dry_run boolean default true
)
returns table(action text, affected_rows bigint)
language plpgsql
as $$
declare
  v_rows bigint;
begin
  with dupes as (
    select id
    from (
      select
        r.id,
        row_number() over (
          partition by r.recommendation_run_id
          order by r.created_at desc, r.id desc
        ) as rn
      from public.recommendations r
    ) t
    where t.rn > 1
  )
  select count(*) into v_rows from dupes;

  if p_dry_run then
    return query select 'dry_run_duplicate_recommendations'::text, coalesce(v_rows, 0);
    return;
  end if;

  delete from public.recommendations r
  where r.id in (
    select id
    from (
      select
        r2.id,
        row_number() over (
          partition by r2.recommendation_run_id
          order by r2.created_at desc, r2.id desc
        ) as rn
      from public.recommendations r2
    ) z
    where z.rn > 1
  );

  get diagnostics v_rows = row_count;
  return query select 'deleted_duplicate_recommendations'::text, coalesce(v_rows, 0);
end;
$$;

-- ---------------------------------------------------------------------------
-- 6) Housekeeping cleanup for old duplicate-criteria runs
--    Deletes runs older than threshold while keeping newest N per criteria.
--    Criteria signature: user_profile_id + strategy_type + input_budget + max_oop.
-- ---------------------------------------------------------------------------

create or replace function public.cleanup_old_recommendation_runs(
  p_keep_latest_per_signature integer default 1,
  p_delete_older_than_days integer default 30,
  p_dry_run boolean default true
)
returns table(action text, affected_rows bigint)
language plpgsql
as $$
declare
  v_candidate_runs bigint;
  v_deleted_recommendations bigint;
  v_deleted_runs bigint;
begin
  if p_keep_latest_per_signature < 1 then
    raise exception 'p_keep_latest_per_signature must be >= 1';
  end if;

  with ranked as (
    select
      rr.id,
      row_number() over (
        partition by rr.user_profile_id, rr.strategy_type, rr.input_budget, rr.max_out_of_pocket
        order by rr.created_at desc, rr.id desc
      ) as rn
    from public.recommendation_runs rr
    where rr.created_at < now() - make_interval(days => p_delete_older_than_days)
      and coalesce(rr.run_status, 'completed') <> 'pending'
  ),
  candidates as (
    select id
    from ranked
    where rn > p_keep_latest_per_signature
  )
  select count(*) into v_candidate_runs from candidates;

  if p_dry_run then
    return query select 'dry_run_candidate_runs'::text, coalesce(v_candidate_runs, 0);
    return;
  end if;

  -- Delete child rows first.
  delete from public.recommendations r
  where r.recommendation_run_id in (
    with ranked as (
      select
        rr.id,
        row_number() over (
          partition by rr.user_profile_id, rr.strategy_type, rr.input_budget, rr.max_out_of_pocket
          order by rr.created_at desc, rr.id desc
        ) as rn
      from public.recommendation_runs rr
      where rr.created_at < now() - make_interval(days => p_delete_older_than_days)
        and coalesce(rr.run_status, 'completed') <> 'pending'
    )
    select id from ranked where rn > p_keep_latest_per_signature
  );
  get diagnostics v_deleted_recommendations = row_count;

  delete from public.recommendation_runs rr
  where rr.id in (
    with ranked as (
      select
        rr2.id,
        row_number() over (
          partition by rr2.user_profile_id, rr2.strategy_type, rr2.input_budget, rr2.max_out_of_pocket
          order by rr2.created_at desc, rr2.id desc
        ) as rn
      from public.recommendation_runs rr2
      where rr2.created_at < now() - make_interval(days => p_delete_older_than_days)
        and coalesce(rr2.run_status, 'completed') <> 'pending'
    )
    select id from ranked where rn > p_keep_latest_per_signature
  );
  get diagnostics v_deleted_runs = row_count;

  return query select 'deleted_recommendations'::text, coalesce(v_deleted_recommendations, 0);
  return query select 'deleted_runs'::text, coalesce(v_deleted_runs, 0);
end;
$$;

